### ISSUE TITLE
Not able to create new files from terminal

### ISSUE THREAD

**Issue by shhdharmen** [stackblitz/tutorialkit#419]
### Describe the bug

Even after keeping `allowRedirects: true` (under terminals > panels) and `watch: true` (under filesystem), we are not able to create new files from terminal. Example: `echo hello > world.txt`. Observe that file is created in webcontainer fs, but not getting reflected in editor's file-tree.

### Link to a StackBlitz project which shows the error

https://stackblitz.com/edit/tutorialkit-api-use-helpbutton-yfxyqb?file=src%2Fcontent%2Ftutorial%2F1-basics%2F1-introduction%2F1-welcome%2Fcontent.mdx

### Steps to reproduce

1. Go to https://stackblitz.com/edit/tutorialkit-api-use-helpbutton-yfxyqb?file=src%2Fcontent%2Ftutorial%2F1-basics%2F1-introduction%2F1-welcome%2Fcontent.mdx
2. Click on "Toggle Terminal"
3. Go to interactive "Terminal"
4. Write command to create file, example `echo hello > world.txt`
5. Observe that file is created in webcontainer's fs using `ls`
6. Observe that file is not reflected in editor's file-tree

### Expected behavior

If we keep `allowRedirects: true`, it should show newly created file in editor's file-tree

For example, if we write `echo hello > world.txt` in interactive terminal, it should create file named "world.txt" in editor's file-tree.

### Screenshots

https://github.com/user-attachments/assets/b8e0d583-56a8-4eb4-b6ad-b32c4e039143

### Platform

- TutorialKit version: 1.3.0
- OS: Window
- Browser: Edge
- Version: 130.0.2849.80

**Comment by AriPerkkio** [comment]
To include new added files into `watch`, you need pass glob patterns that match these files. It's recommended to be as specific as possible with these patterns. So based on your reproduction something like below should work:

```md
filesystem:
  watch: ['/hello.txt']
```

Watching whole file system for new files is expensive for performance - that's why `filesystem.watch: true` won't consider newly added files, it only watches existing files.

https://tutorialkit.dev/reference/configuration/#filesystem

**Comment by shhdharmen** [comment]
Thanks for your prompt response!
