### ISSUE TITLE
Console errors on npm run dev

### ISSUE THREAD

**Issue by dvelikiy** [stackblitz/tutorialkit#54]
### Describe the bug

![image](https://github.com/stackblitz/tutorialkit/assets/3008203/d99b91b9-7ac0-4b90-8617-86204469c2d3)

### Steps to reproduce

npm i
npm run dev

### Expected behavior

no errors

### Platform

Windows, Chrome. Node 20, npm 10.7.0

**Comment by TO-smichaelsen** [comment]
Hi. i ran into the same issue :/

**Comment by miller-danilo** [comment]
Hi, the error persists using CMD, it is because in the `node_modules\@tutorialkit\astro\dist\index.js` there are a replaceAll('/', '-'), this not work in windows because the path separator is "\\" not "/". 

After replace, the encodeURIComponent transform "\\" into `%5C` generating something like `template%5Cdefault.json`. 

![image](https://github.com/stackblitz/tutorialkit/assets/392170/a453cccf-bfc6-40f5-911d-ac2fbf23f359)

![image](https://github.com/stackblitz/tutorialkit/assets/392170/6d821fcf-728f-4453-a0af-d0597bc92d9b)


A solution can be use the path.sep to get the environment separator:

![image](https://github.com/stackblitz/tutorialkit/assets/392170/3a667006-dd9d-461f-b7fe-1ebbaaa958cf)

**Comment by mvargaslandolfi1993** [comment]
The other solution that i was found its installing 

npm i @astrojs/vue --save-dev

But what you mention is a better alternative. It's just something that needs to be modified directly in the astro package.

**Comment by Nemikolh** [comment]
Thanks @miller-danilo for finding the fix! :smiley: Would you like to submit a PR for it?

Looks like there are also CSS issues on Windows which might be caused by a similar reason. I'm actually curious if anyone on Windows could try doing:

```bash
node -p "require('fast-glob').globSync(require.resolve('@tutorialkit/components-react'), '../**/*.js')"
```

My guess is that this should return an empty array on windows but it would be nice to double check.
